#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $DATASTORE_DB;
    GRANT ALL PRIVILEGES ON DATABASE $DATASTORE_DB TO $POSTGRES_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" "$DATASTORE_DB" <<-EOSQL
    CREATE EXTENSION postgis;
    GRANT ALL ON geometry_columns TO PUBLIC;
    GRANT ALL ON spatial_ref_sys TO PUBLIC;
EOSQL